pipeline {

    // Instructs Jenkins to use the buildconductor docker image to run this pipeline Test
    
    agent {
        docker { 
            image 'greghodgkinson/jenkins-buildconductor-iib:edge' 
            label 'docker'
            args '-u root'
        }
        
    }

    stages {
    
        // Pull down source code from Git repo
        
       stage('Checkout Code'){
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'load']], submoduleCfg: [], userRemoteConfigs: [[url: 'git@github.com:sitaramaprasad-e/temp-convert-github-iib.git']]])
            }
       }   
       
              
       // Build BAR file from source code
       
        stage('Build BAR') {
            steps {
                sh "/buildconductor/iib/run-automation.sh build tempconvert TemperatureConverter" 
            }
        }  
	    stage('Save BAR'){
		    steps{
			sh "cp /var/lib/jenkins/workspace/savebar-iib/output/tempconvert.bar /var/lib/jenkins/workspace/savebar-iib/ "
			sh "cd /var/lib/jenkins/workspace/savebar-iib/ "
			sh 'git config --global user.email "sitaramaprasad.erothu@gmail.com" '
			sh 'git config --global user.name "sitaramaprasad-e" '
			withCredentials([usernamePassword(credentialsId: 'git-pass-58e2f3a9-5a02-4229-a3a8-943f4d52539a', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        // sh("git tag -a some_tag -m 'Jenkins'")
			sh "git add tempconvert.bar"
			sh 'git commit -m "Added bar file to the repo from pipeline" '
			sh "git push -u origin HEAD:master"
			}
			sshagent (credentials: ['git-ssh-58e2f3a9-5a02-4229-a3a8-943f4d52539a']) {
             		sh("git tag -a some_tag -m 'Jenkins'")
            		sh "git push -u origin HEAD:master"
			}
			}
		    }
	
		    
	    }
        
            
    }
