pipeline {

    // Instructs Jenkins to use the buildconductor docker image to run this pipeline Test
    
    agent {
        docker { 
            image 'greghodgkinson/jenkins-buildconductor-iib:edge' 
            label 'docker'
            args '-u root'
        }
        
    }

    stages {
    
        // Pull down source code from Git repo
        
       stage('Checkout Code'){
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'load']], submoduleCfg: [], userRemoteConfigs: [[url: 'git@github.com:sitaramaprasad-e/temp-convert-github-iib.git']]])
            }
       }   
       
              
       // Build BAR file from source code
       
        stage('Build BAR') {
            steps {
                sh "/buildconductor/iib/run-automation.sh build tempconvert TemperatureConverter" 
            }
        }  
	    stage('Save BAR'){
		    steps{
			sh "cp /var/lib/jenkins/workspace/savebar-iib/output/tempconvert.bar /var/lib/jenkins/workspace/savebar-iib/ "
			sh "cd /var/lib/jenkins/workspace/savebar-iib/ "
			withCredentials([usernamePassword(credentialsId: '58e2f3a9-5a02-4229-a3a8-943f4d52539a', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh("git tag -a some_tag -m 'Jenkins'")
			sh "('git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com:sitaramaprasad-e/temp-convert-github-iib.git')"
                
			}
	sshagent (credentials: ['git-ssh-credentials-ID']) {
             sh("git tag -a some_tag -m 'Jenkins'")
             sh "('git push git@github.com:sitaramaprasad-e/temp-convert-github-iib.git')"	
		
	}
		    
	    }
        
            
    }

}
